/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'status' : BookingStatus,
  'guestIdProof' : [] | [string],
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'checkInDate' : Timestamp,
  'guestName' : string,
  'pricePerDay' : number,
  'expectedCheckOutDate' : Timestamp,
  'actualCheckOutDate' : [] | [Timestamp],
  'advancePayment' : number,
  'guestPhone' : string,
  'roomId' : bigint,
}
export type BookingStatus = { 'Active' : null } |
  { 'Cancelled' : null } |
  { 'CheckedOut' : null };
export interface DashboardStats {
  'occupiedRooms' : bigint,
  'availableRooms' : bigint,
  'todayCheckIns' : bigint,
  'todayRevenue' : number,
  'maintenanceRooms' : bigint,
  'totalRooms' : bigint,
}
export interface Invoice {
  'id' : bigint,
  'paymentStatus' : PaymentStatus,
  'paymentMethod' : [] | [PaymentMethod],
  'bookingId' : bigint,
  'roomCharges' : number,
  'createdAt' : bigint,
  'totalAmount' : number,
  'advancePaid' : number,
  'discount' : number,
  'extraCharges' : number,
  'dueAmount' : number,
}
export type PaymentMethod = { 'UPI' : null } |
  { 'Cash' : null };
export type PaymentStatus = { 'PartiallyPaid' : null } |
  { 'Paid' : null } |
  { 'Pending' : null };
export type Result = { 'ok' : null } |
  { 'err' : string };
export type Result_1 = { 'ok' : StaffUser } |
  { 'err' : string };
export type Result__1 = { 'ok' : Room } |
  { 'err' : string };
export type Result__2 = { 'ok' : Booking } |
  { 'err' : string };
export type Result__3 = { 'ok' : Invoice } |
  { 'err' : string };
export interface Room {
  'id' : bigint,
  'status' : RoomStatus,
  'createdAt' : Timestamp,
  'pricePerDay' : number,
  'number' : string,
  'roomType' : RoomType,
}
export type RoomStatus = { 'Available' : null } |
  { 'Maintenance' : null } |
  { 'Occupied' : null };
export type RoomType = { 'AcDouble' : null } |
  { 'AcDeluxe' : null } |
  { 'Double' : null } |
  { 'AcSingle' : null } |
  { 'Deluxe' : null } |
  { 'Single' : null };
export interface StaffUser {
  'principal' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'isActive' : boolean,
  'email' : string,
}
export type Timestamp = bigint;
export type UserId = Principal;
export type UserRole = { 'Staff' : null } |
  { 'Admin' : null };
export interface _SERVICE {
  'addRoom' : ActorMethod<[string, RoomType, number], Result__1>,
  'addUser' : ActorMethod<[Principal, string, string, UserRole], Result_1>,
  'cancelBooking' : ActorMethod<[bigint, string], Result>,
  'checkout' : ActorMethod<
    [bigint, bigint, number, number, PaymentMethod, number],
    Result__3
  >,
  'createBooking' : ActorMethod<
    [string, string, [] | [string], bigint, bigint, bigint, number],
    Result__2
  >,
  'deactivateUser' : ActorMethod<[Principal], Result>,
  'deleteRoom' : ActorMethod<[bigint], Result>,
  'getActiveBookings' : ActorMethod<[], Array<Booking>>,
  'getAvailableRooms' : ActorMethod<[], Array<Room>>,
  'getBookingById' : ActorMethod<[bigint], [] | [Booking]>,
  'getBookingHistory' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<Booking>
  >,
  'getBookings' : ActorMethod<[[] | [BookingStatus]], Array<Booking>>,
  'getDailyRevenue' : ActorMethod<[bigint], number>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getInvoice' : ActorMethod<[bigint], [] | [Invoice]>,
  'getInvoices' : ActorMethod<[], Array<Invoice>>,
  'getInvoicesByDateRange' : ActorMethod<[bigint, bigint], Array<Invoice>>,
  'getPendingInvoices' : ActorMethod<[], Array<Invoice>>,
  'getRoomById' : ActorMethod<[bigint], [] | [Room]>,
  'getRooms' : ActorMethod<[], Array<Room>>,
  'getUserRole' : ActorMethod<[Principal], [] | [UserRole]>,
  'getUsers' : ActorMethod<[], Array<StaffUser>>,
  'isAdminQuery' : ActorMethod<[Principal], boolean>,
  'updateBooking' : ActorMethod<
    [bigint, [] | [bigint], [] | [number]],
    Result__2
  >,
  'updateRoom' : ActorMethod<
    [bigint, [] | [string], [] | [RoomType], [] | [number], [] | [RoomStatus]],
    Result__1
  >,
  'updateUserRole' : ActorMethod<[Principal, UserRole], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];