/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RoomType = IDL.Variant({
  'AcDouble' : IDL.Null,
  'AcDeluxe' : IDL.Null,
  'Double' : IDL.Null,
  'AcSingle' : IDL.Null,
  'Deluxe' : IDL.Null,
  'Single' : IDL.Null,
});
export const RoomStatus = IDL.Variant({
  'Available' : IDL.Null,
  'Maintenance' : IDL.Null,
  'Occupied' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Room = IDL.Record({
  'id' : IDL.Nat,
  'status' : RoomStatus,
  'createdAt' : Timestamp,
  'pricePerDay' : IDL.Float64,
  'number' : IDL.Text,
  'roomType' : RoomType,
});
export const Result__1 = IDL.Variant({ 'ok' : Room, 'err' : IDL.Text });
export const UserRole = IDL.Variant({ 'Staff' : IDL.Null, 'Admin' : IDL.Null });
export const UserId = IDL.Principal;
export const StaffUser = IDL.Record({
  'principal' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
});
export const Result_1 = IDL.Variant({ 'ok' : StaffUser, 'err' : IDL.Text });
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const PaymentMethod = IDL.Variant({
  'UPI' : IDL.Null,
  'Cash' : IDL.Null,
});
export const PaymentStatus = IDL.Variant({
  'PartiallyPaid' : IDL.Null,
  'Paid' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Invoice = IDL.Record({
  'id' : IDL.Nat,
  'paymentStatus' : PaymentStatus,
  'paymentMethod' : IDL.Opt(PaymentMethod),
  'bookingId' : IDL.Nat,
  'roomCharges' : IDL.Float64,
  'createdAt' : IDL.Int,
  'totalAmount' : IDL.Float64,
  'advancePaid' : IDL.Float64,
  'discount' : IDL.Float64,
  'extraCharges' : IDL.Float64,
  'dueAmount' : IDL.Float64,
});
export const Result__3 = IDL.Variant({ 'ok' : Invoice, 'err' : IDL.Text });
export const BookingStatus = IDL.Variant({
  'Active' : IDL.Null,
  'Cancelled' : IDL.Null,
  'CheckedOut' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'status' : BookingStatus,
  'guestIdProof' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'checkInDate' : Timestamp,
  'guestName' : IDL.Text,
  'pricePerDay' : IDL.Float64,
  'expectedCheckOutDate' : Timestamp,
  'actualCheckOutDate' : IDL.Opt(Timestamp),
  'advancePayment' : IDL.Float64,
  'guestPhone' : IDL.Text,
  'roomId' : IDL.Nat,
});
export const Result__2 = IDL.Variant({ 'ok' : Booking, 'err' : IDL.Text });
export const DashboardStats = IDL.Record({
  'occupiedRooms' : IDL.Nat,
  'availableRooms' : IDL.Nat,
  'todayCheckIns' : IDL.Nat,
  'todayRevenue' : IDL.Float64,
  'maintenanceRooms' : IDL.Nat,
  'totalRooms' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addRoom' : IDL.Func([IDL.Text, RoomType, IDL.Float64], [Result__1], []),
  'addUser' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, UserRole],
      [Result_1],
      [],
    ),
  'cancelBooking' : IDL.Func([IDL.Nat, IDL.Text], [Result], []),
  'checkout' : IDL.Func(
      [IDL.Nat, IDL.Int, IDL.Float64, IDL.Float64, PaymentMethod, IDL.Float64],
      [Result__3],
      [],
    ),
  'createBooking' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Nat,
        IDL.Int,
        IDL.Int,
        IDL.Float64,
      ],
      [Result__2],
      [],
    ),
  'deactivateUser' : IDL.Func([IDL.Principal], [Result], []),
  'deleteRoom' : IDL.Func([IDL.Nat], [Result], []),
  'getActiveBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAvailableRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
  'getBookingById' : IDL.Func([IDL.Nat], [IDL.Opt(Booking)], ['query']),
  'getBookingHistory' : IDL.Func(
      [IDL.Opt(IDL.Int), IDL.Opt(IDL.Int)],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getBookings' : IDL.Func(
      [IDL.Opt(BookingStatus)],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getDailyRevenue' : IDL.Func([IDL.Int], [IDL.Float64], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getInvoice' : IDL.Func([IDL.Nat], [IDL.Opt(Invoice)], ['query']),
  'getInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getInvoicesByDateRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(Invoice)],
      ['query'],
    ),
  'getPendingInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getRoomById' : IDL.Func([IDL.Nat], [IDL.Opt(Room)], ['query']),
  'getRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
  'getUserRole' : IDL.Func([IDL.Principal], [IDL.Opt(UserRole)], ['query']),
  'getUsers' : IDL.Func([], [IDL.Vec(StaffUser)], ['query']),
  'isAdminQuery' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'updateBooking' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Int), IDL.Opt(IDL.Float64)],
      [Result__2],
      [],
    ),
  'updateRoom' : IDL.Func(
      [
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Opt(RoomType),
        IDL.Opt(IDL.Float64),
        IDL.Opt(RoomStatus),
      ],
      [Result__1],
      [],
    ),
  'updateUserRole' : IDL.Func([IDL.Principal, UserRole], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RoomType = IDL.Variant({
    'AcDouble' : IDL.Null,
    'AcDeluxe' : IDL.Null,
    'Double' : IDL.Null,
    'AcSingle' : IDL.Null,
    'Deluxe' : IDL.Null,
    'Single' : IDL.Null,
  });
  const RoomStatus = IDL.Variant({
    'Available' : IDL.Null,
    'Maintenance' : IDL.Null,
    'Occupied' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Room = IDL.Record({
    'id' : IDL.Nat,
    'status' : RoomStatus,
    'createdAt' : Timestamp,
    'pricePerDay' : IDL.Float64,
    'number' : IDL.Text,
    'roomType' : RoomType,
  });
  const Result__1 = IDL.Variant({ 'ok' : Room, 'err' : IDL.Text });
  const UserRole = IDL.Variant({ 'Staff' : IDL.Null, 'Admin' : IDL.Null });
  const UserId = IDL.Principal;
  const StaffUser = IDL.Record({
    'principal' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : UserRole,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
  });
  const Result_1 = IDL.Variant({ 'ok' : StaffUser, 'err' : IDL.Text });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const PaymentMethod = IDL.Variant({ 'UPI' : IDL.Null, 'Cash' : IDL.Null });
  const PaymentStatus = IDL.Variant({
    'PartiallyPaid' : IDL.Null,
    'Paid' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Invoice = IDL.Record({
    'id' : IDL.Nat,
    'paymentStatus' : PaymentStatus,
    'paymentMethod' : IDL.Opt(PaymentMethod),
    'bookingId' : IDL.Nat,
    'roomCharges' : IDL.Float64,
    'createdAt' : IDL.Int,
    'totalAmount' : IDL.Float64,
    'advancePaid' : IDL.Float64,
    'discount' : IDL.Float64,
    'extraCharges' : IDL.Float64,
    'dueAmount' : IDL.Float64,
  });
  const Result__3 = IDL.Variant({ 'ok' : Invoice, 'err' : IDL.Text });
  const BookingStatus = IDL.Variant({
    'Active' : IDL.Null,
    'Cancelled' : IDL.Null,
    'CheckedOut' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'status' : BookingStatus,
    'guestIdProof' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'createdBy' : UserId,
    'checkInDate' : Timestamp,
    'guestName' : IDL.Text,
    'pricePerDay' : IDL.Float64,
    'expectedCheckOutDate' : Timestamp,
    'actualCheckOutDate' : IDL.Opt(Timestamp),
    'advancePayment' : IDL.Float64,
    'guestPhone' : IDL.Text,
    'roomId' : IDL.Nat,
  });
  const Result__2 = IDL.Variant({ 'ok' : Booking, 'err' : IDL.Text });
  const DashboardStats = IDL.Record({
    'occupiedRooms' : IDL.Nat,
    'availableRooms' : IDL.Nat,
    'todayCheckIns' : IDL.Nat,
    'todayRevenue' : IDL.Float64,
    'maintenanceRooms' : IDL.Nat,
    'totalRooms' : IDL.Nat,
  });
  
  return IDL.Service({
    'addRoom' : IDL.Func([IDL.Text, RoomType, IDL.Float64], [Result__1], []),
    'addUser' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, UserRole],
        [Result_1],
        [],
      ),
    'cancelBooking' : IDL.Func([IDL.Nat, IDL.Text], [Result], []),
    'checkout' : IDL.Func(
        [
          IDL.Nat,
          IDL.Int,
          IDL.Float64,
          IDL.Float64,
          PaymentMethod,
          IDL.Float64,
        ],
        [Result__3],
        [],
      ),
    'createBooking' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Nat,
          IDL.Int,
          IDL.Int,
          IDL.Float64,
        ],
        [Result__2],
        [],
      ),
    'deactivateUser' : IDL.Func([IDL.Principal], [Result], []),
    'deleteRoom' : IDL.Func([IDL.Nat], [Result], []),
    'getActiveBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAvailableRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
    'getBookingById' : IDL.Func([IDL.Nat], [IDL.Opt(Booking)], ['query']),
    'getBookingHistory' : IDL.Func(
        [IDL.Opt(IDL.Int), IDL.Opt(IDL.Int)],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getBookings' : IDL.Func(
        [IDL.Opt(BookingStatus)],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getDailyRevenue' : IDL.Func([IDL.Int], [IDL.Float64], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getInvoice' : IDL.Func([IDL.Nat], [IDL.Opt(Invoice)], ['query']),
    'getInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getInvoicesByDateRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(Invoice)],
        ['query'],
      ),
    'getPendingInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getRoomById' : IDL.Func([IDL.Nat], [IDL.Opt(Room)], ['query']),
    'getRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
    'getUserRole' : IDL.Func([IDL.Principal], [IDL.Opt(UserRole)], ['query']),
    'getUsers' : IDL.Func([], [IDL.Vec(StaffUser)], ['query']),
    'isAdminQuery' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'updateBooking' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Int), IDL.Opt(IDL.Float64)],
        [Result__2],
        [],
      ),
    'updateRoom' : IDL.Func(
        [
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(RoomType),
          IDL.Opt(IDL.Float64),
          IDL.Opt(RoomStatus),
        ],
        [Result__1],
        [],
      ),
    'updateUserRole' : IDL.Func([IDL.Principal, UserRole], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };