/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export type Result__3 = {
    __kind__: "ok";
    ok: Invoice;
} | {
    __kind__: "err";
    err: string;
};
export type Result__1 = {
    __kind__: "ok";
    ok: Room;
} | {
    __kind__: "err";
    err: string;
};
export interface Room {
    id: bigint;
    status: RoomStatus;
    createdAt: Timestamp;
    pricePerDay: number;
    number: string;
    roomType: RoomType;
}
export type Result_1 = {
    __kind__: "ok";
    ok: StaffUser;
} | {
    __kind__: "err";
    err: string;
};
export interface Invoice {
    id: bigint;
    paymentStatus: PaymentStatus;
    paymentMethod?: PaymentMethod;
    bookingId: bigint;
    roomCharges: number;
    createdAt: bigint;
    totalAmount: number;
    advancePaid: number;
    discount: number;
    extraCharges: number;
    dueAmount: number;
}
export interface DashboardStats {
    occupiedRooms: bigint;
    availableRooms: bigint;
    todayCheckIns: bigint;
    todayRevenue: number;
    maintenanceRooms: bigint;
    totalRooms: bigint;
}
export type UserId = Principal;
export interface StaffUser {
    principal: UserId;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    isActive: boolean;
    email: string;
}
export type Result = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export type Result__2 = {
    __kind__: "ok";
    ok: Booking;
} | {
    __kind__: "err";
    err: string;
};
export interface Booking {
    id: bigint;
    status: BookingStatus;
    guestIdProof?: string;
    createdAt: Timestamp;
    createdBy: UserId;
    checkInDate: Timestamp;
    guestName: string;
    pricePerDay: number;
    expectedCheckOutDate: Timestamp;
    actualCheckOutDate?: Timestamp;
    advancePayment: number;
    guestPhone: string;
    roomId: bigint;
}
export enum BookingStatus {
    Active = "Active",
    Cancelled = "Cancelled",
    CheckedOut = "CheckedOut"
}
export enum PaymentMethod {
    UPI = "UPI",
    Cash = "Cash"
}
export enum PaymentStatus {
    PartiallyPaid = "PartiallyPaid",
    Paid = "Paid",
    Pending = "Pending"
}
export enum RoomStatus {
    Available = "Available",
    Maintenance = "Maintenance",
    Occupied = "Occupied"
}
export enum RoomType {
    AcDouble = "AcDouble",
    AcDeluxe = "AcDeluxe",
    Double = "Double",
    AcSingle = "AcSingle",
    Deluxe = "Deluxe",
    Single = "Single"
}
export enum UserRole {
    Staff = "Staff",
    Admin = "Admin"
}
export interface backendInterface {
    addRoom(number: string, roomType: RoomType, pricePerDay: number): Promise<Result__1>;
    addUser(principal: Principal, name: string, email: string, role: UserRole): Promise<Result_1>;
    cancelBooking(id: bigint, reason: string): Promise<Result>;
    checkout(bookingId: bigint, actualCheckOutDate: bigint, extraCharges: number, discount: number, paymentMethod: PaymentMethod, amountPaid: number): Promise<Result__3>;
    createBooking(guestName: string, guestPhone: string, guestIdProof: string | null, roomId: bigint, checkInDate: bigint, expectedCheckOutDate: bigint, advancePayment: number): Promise<Result__2>;
    deactivateUser(principal: Principal): Promise<Result>;
    deleteRoom(id: bigint): Promise<Result>;
    getActiveBookings(): Promise<Array<Booking>>;
    getAvailableRooms(): Promise<Array<Room>>;
    getBookingById(id: bigint): Promise<Booking | null>;
    getBookingHistory(startDate: bigint | null, endDate: bigint | null): Promise<Array<Booking>>;
    getBookings(status: BookingStatus | null): Promise<Array<Booking>>;
    getDailyRevenue(date: bigint): Promise<number>;
    getDashboardStats(): Promise<DashboardStats>;
    getInvoice(bookingId: bigint): Promise<Invoice | null>;
    getInvoices(): Promise<Array<Invoice>>;
    getInvoicesByDateRange(startDate: bigint, endDate: bigint): Promise<Array<Invoice>>;
    getPendingInvoices(): Promise<Array<Invoice>>;
    getRoomById(id: bigint): Promise<Room | null>;
    getRooms(): Promise<Array<Room>>;
    getUserRole(principal: Principal): Promise<UserRole | null>;
    getUsers(): Promise<Array<StaffUser>>;
    isAdminQuery(principal: Principal): Promise<boolean>;
    updateBooking(id: bigint, expectedCheckOutDate: bigint | null, advancePayment: number | null): Promise<Result__2>;
    updateRoom(id: bigint, number: string | null, roomType: RoomType | null, pricePerDay: number | null, status: RoomStatus | null): Promise<Result__1>;
    updateUserRole(principal: Principal, role: UserRole): Promise<Result>;
}
import type { Booking as _Booking, BookingStatus as _BookingStatus, Invoice as _Invoice, PaymentMethod as _PaymentMethod, PaymentStatus as _PaymentStatus, Result as _Result, Result_1 as _Result_1, Result__1 as _Result__1, Result__2 as _Result__2, Result__3 as _Result__3, Room as _Room, RoomStatus as _RoomStatus, RoomType as _RoomType, StaffUser as _StaffUser, Timestamp as _Timestamp, UserId as _UserId, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addRoom(arg0: string, arg1: RoomType, arg2: number): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor.addRoom(arg0, to_candid_RoomType_n1(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_Result__1_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRoom(arg0, to_candid_RoomType_n1(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_Result__1_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async addUser(arg0: Principal, arg1: string, arg2: string, arg3: UserRole): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.addUser(arg0, arg1, arg2, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg3));
                return from_candid_Result_1_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addUser(arg0, arg1, arg2, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg3));
            return from_candid_Result_1_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async cancelBooking(arg0: bigint, arg1: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelBooking(arg0, arg1);
                return from_candid_Result_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelBooking(arg0, arg1);
            return from_candid_Result_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async checkout(arg0: bigint, arg1: bigint, arg2: number, arg3: number, arg4: PaymentMethod, arg5: number): Promise<Result__3> {
        if (this.processError) {
            try {
                const result = await this.actor.checkout(arg0, arg1, arg2, arg3, to_candid_PaymentMethod_n21(this._uploadFile, this._downloadFile, arg4), arg5);
                return from_candid_Result__3_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkout(arg0, arg1, arg2, arg3, to_candid_PaymentMethod_n21(this._uploadFile, this._downloadFile, arg4), arg5);
            return from_candid_Result__3_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async createBooking(arg0: string, arg1: string, arg2: string | null, arg3: bigint, arg4: bigint, arg5: bigint, arg6: number): Promise<Result__2> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(arg0, arg1, to_candid_opt_n32(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6);
                return from_candid_Result__2_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(arg0, arg1, to_candid_opt_n32(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6);
            return from_candid_Result__2_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async deactivateUser(arg0: Principal): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateUser(arg0);
                return from_candid_Result_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateUser(arg0);
            return from_candid_Result_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteRoom(arg0: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRoom(arg0);
                return from_candid_Result_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRoom(arg0);
            return from_candid_Result_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActiveBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveBookings();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveBookings();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableRooms(): Promise<Array<Room>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableRooms();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableRooms();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingById(arg0: bigint): Promise<Booking | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingById(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingById(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingHistory(arg0: bigint | null, arg1: bigint | null): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingHistory(to_candid_opt_n44(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n44(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingHistory(to_candid_opt_n44(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n44(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookings(arg0: BookingStatus | null): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookings(to_candid_opt_n45(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookings(to_candid_opt_n45(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyRevenue(arg0: bigint): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyRevenue(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyRevenue(arg0);
            return result;
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getInvoice(arg0: bigint): Promise<Invoice | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoice(arg0);
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoice(arg0);
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvoices(): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoices();
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoices();
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvoicesByDateRange(arg0: bigint, arg1: bigint): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoicesByDateRange(arg0, arg1);
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoicesByDateRange(arg0, arg1);
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingInvoices(): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingInvoices();
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingInvoices();
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoomById(arg0: bigint): Promise<Room | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoomById(arg0);
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoomById(arg0);
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRooms(): Promise<Array<Room>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRooms();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRooms();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserRole(arg0: Principal): Promise<UserRole | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserRole(arg0);
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserRole(arg0);
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUsers(): Promise<Array<StaffUser>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsers();
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsers();
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdminQuery(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdminQuery(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdminQuery(arg0);
            return result;
        }
    }
    async updateBooking(arg0: bigint, arg1: bigint | null, arg2: number | null): Promise<Result__2> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBooking(arg0, to_candid_opt_n44(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n53(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Result__2_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBooking(arg0, to_candid_opt_n44(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n53(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Result__2_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateRoom(arg0: bigint, arg1: string | null, arg2: RoomType | null, arg3: number | null, arg4: RoomStatus | null): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRoom(arg0, to_candid_opt_n32(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n54(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n53(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n55(this._uploadFile, this._downloadFile, arg4));
                return from_candid_Result__1_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRoom(arg0, to_candid_opt_n32(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n54(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n53(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n55(this._uploadFile, this._downloadFile, arg4));
            return from_candid_Result__1_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUserRole(arg0: Principal, arg1: UserRole): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_n19(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BookingStatus_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Invoice_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Invoice): Invoice {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Result__2_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__2): Result__2 {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Result__3_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__3): Result__3 {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_RoomStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoomStatus): RoomStatus {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_RoomType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoomType): RoomType {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Room_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Room): Room {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_StaffUser_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StaffUser): StaffUser {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PaymentMethod]): PaymentMethod | null {
    return value.length === 0 ? null : from_candid_PaymentMethod_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Booking]): Booking | null {
    return value.length === 0 ? null : from_candid_Booking_n35(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Invoice]): Invoice | null {
    return value.length === 0 ? null : from_candid_Invoice_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Room]): Room | null {
    return value.length === 0 ? null : from_candid_Room_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserRole]): UserRole | null {
    return value.length === 0 ? null : from_candid_UserRole_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: _UserId;
    name: string;
    createdAt: _Timestamp;
    role: _UserRole;
    isActive: boolean;
    email: string;
}): {
    principal: UserId;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    isActive: boolean;
    email: string;
} {
    return {
        principal: value.principal,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n17(_uploadFile, _downloadFile, value.role),
        isActive: value.isActive,
        email: value.email
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    paymentStatus: _PaymentStatus;
    paymentMethod: [] | [_PaymentMethod];
    bookingId: bigint;
    roomCharges: number;
    createdAt: bigint;
    totalAmount: number;
    advancePaid: number;
    discount: number;
    extraCharges: number;
    dueAmount: number;
}): {
    id: bigint;
    paymentStatus: PaymentStatus;
    paymentMethod?: PaymentMethod;
    bookingId: bigint;
    roomCharges: number;
    createdAt: bigint;
    totalAmount: number;
    advancePaid: number;
    discount: number;
    extraCharges: number;
    dueAmount: number;
} {
    return {
        id: value.id,
        paymentStatus: from_candid_PaymentStatus_n27(_uploadFile, _downloadFile, value.paymentStatus),
        paymentMethod: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.paymentMethod)),
        bookingId: value.bookingId,
        roomCharges: value.roomCharges,
        createdAt: value.createdAt,
        totalAmount: value.totalAmount,
        advancePaid: value.advancePaid,
        discount: value.discount,
        extraCharges: value.extraCharges,
        dueAmount: value.dueAmount
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _BookingStatus;
    guestIdProof: [] | [string];
    createdAt: _Timestamp;
    createdBy: _UserId;
    checkInDate: _Timestamp;
    guestName: string;
    pricePerDay: number;
    expectedCheckOutDate: _Timestamp;
    actualCheckOutDate: [] | [_Timestamp];
    advancePayment: number;
    guestPhone: string;
    roomId: bigint;
}): {
    id: bigint;
    status: BookingStatus;
    guestIdProof?: string;
    createdAt: Timestamp;
    createdBy: UserId;
    checkInDate: Timestamp;
    guestName: string;
    pricePerDay: number;
    expectedCheckOutDate: Timestamp;
    actualCheckOutDate?: Timestamp;
    advancePayment: number;
    guestPhone: string;
    roomId: bigint;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n37(_uploadFile, _downloadFile, value.status),
        guestIdProof: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.guestIdProof)),
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        checkInDate: value.checkInDate,
        guestName: value.guestName,
        pricePerDay: value.pricePerDay,
        expectedCheckOutDate: value.expectedCheckOutDate,
        actualCheckOutDate: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.actualCheckOutDate)),
        advancePayment: value.advancePayment,
        guestPhone: value.guestPhone,
        roomId: value.roomId
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _RoomStatus;
    createdAt: _Timestamp;
    pricePerDay: number;
    number: string;
    roomType: _RoomType;
}): {
    id: bigint;
    status: RoomStatus;
    createdAt: Timestamp;
    pricePerDay: number;
    number: string;
    roomType: RoomType;
} {
    return {
        id: value.id,
        status: from_candid_RoomStatus_n7(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        pricePerDay: value.pricePerDay,
        number: value.number,
        roomType: from_candid_RoomType_n9(_uploadFile, _downloadFile, value.roomType)
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    AcDouble: null;
} | {
    AcDeluxe: null;
} | {
    Double: null;
} | {
    AcSingle: null;
} | {
    Deluxe: null;
} | {
    Single: null;
}): RoomType {
    return "AcDouble" in value ? RoomType.AcDouble : "AcDeluxe" in value ? RoomType.AcDeluxe : "Double" in value ? RoomType.Double : "AcSingle" in value ? RoomType.AcSingle : "Deluxe" in value ? RoomType.Deluxe : "Single" in value ? RoomType.Single : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _StaffUser;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: StaffUser;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_StaffUser_n15(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Staff: null;
} | {
    Admin: null;
}): UserRole {
    return "Staff" in value ? UserRole.Staff : "Admin" in value ? UserRole.Admin : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Invoice;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Invoice;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Invoice_n25(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    PartiallyPaid: null;
} | {
    Paid: null;
} | {
    Pending: null;
}): PaymentStatus {
    return "PartiallyPaid" in value ? PaymentStatus.PartiallyPaid : "Paid" in value ? PaymentStatus.Paid : "Pending" in value ? PaymentStatus.Pending : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    UPI: null;
} | {
    Cash: null;
}): PaymentMethod {
    return "UPI" in value ? PaymentMethod.UPI : "Cash" in value ? PaymentMethod.Cash : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Booking;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Booking;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Booking_n35(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Active: null;
} | {
    Cancelled: null;
} | {
    CheckedOut: null;
}): BookingStatus {
    return "Active" in value ? BookingStatus.Active : "Cancelled" in value ? BookingStatus.Cancelled : "CheckedOut" in value ? BookingStatus.CheckedOut : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Room;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Room;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Room_n5(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Available: null;
} | {
    Maintenance: null;
} | {
    Occupied: null;
}): RoomStatus {
    return "Available" in value ? RoomStatus.Available : "Maintenance" in value ? RoomStatus.Maintenance : "Occupied" in value ? RoomStatus.Occupied : value;
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Room>): Array<Room> {
    return value.map((x)=>from_candid_Room_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Invoice>): Array<Invoice> {
    return value.map((x)=>from_candid_Invoice_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StaffUser>): Array<StaffUser> {
    return value.map((x)=>from_candid_StaffUser_n15(_uploadFile, _downloadFile, x));
}
function to_candid_BookingStatus_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_RoomStatus_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoomStatus): _RoomStatus {
    return to_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function to_candid_RoomType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoomType): _RoomType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus | null): [] | [_BookingStatus] {
    return value === null ? candid_none() : candid_some(to_candid_BookingStatus_n46(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoomType | null): [] | [_RoomType] {
    return value === null ? candid_none() : candid_some(to_candid_RoomType_n1(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoomStatus | null): [] | [_RoomStatus] {
    return value === null ? candid_none() : candid_some(to_candid_RoomStatus_n56(_uploadFile, _downloadFile, value));
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    Staff: null;
} | {
    Admin: null;
} {
    return value == UserRole.Staff ? {
        Staff: null
    } : value == UserRole.Admin ? {
        Admin: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoomType): {
    AcDouble: null;
} | {
    AcDeluxe: null;
} | {
    Double: null;
} | {
    AcSingle: null;
} | {
    Deluxe: null;
} | {
    Single: null;
} {
    return value == RoomType.AcDouble ? {
        AcDouble: null
    } : value == RoomType.AcDeluxe ? {
        AcDeluxe: null
    } : value == RoomType.Double ? {
        Double: null
    } : value == RoomType.AcSingle ? {
        AcSingle: null
    } : value == RoomType.Deluxe ? {
        Deluxe: null
    } : value == RoomType.Single ? {
        Single: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    UPI: null;
} | {
    Cash: null;
} {
    return value == PaymentMethod.UPI ? {
        UPI: null
    } : value == PaymentMethod.Cash ? {
        Cash: null
    } : value;
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    Active: null;
} | {
    Cancelled: null;
} | {
    CheckedOut: null;
} {
    return value == BookingStatus.Active ? {
        Active: null
    } : value == BookingStatus.Cancelled ? {
        Cancelled: null
    } : value == BookingStatus.CheckedOut ? {
        CheckedOut: null
    } : value;
}
function to_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RoomStatus): {
    Available: null;
} | {
    Maintenance: null;
} | {
    Occupied: null;
} {
    return value == RoomStatus.Available ? {
        Available: null
    } : value == RoomStatus.Maintenance ? {
        Maintenance: null
    } : value == RoomStatus.Occupied ? {
        Occupied: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
